#!/system/bin/sh
# DroidTheory + DHO / Redone for VentureROM by Topazstix

# Kernel Tweaks
#
echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
echo "ondemand" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
busybox sysctl -w kernel.panic=0
busybox sysctl -w kernel.panic_on_oops=1
busybox sysctl -w kernel.sampling_rate=15000
busybox sysctl -w kernel.up_threshold=15
busybox sysctl -w kernel.ignore_nice_load=1

# Battery Tweaks
busybox sysctl -w kernel.random.write_wakeup_threshold=256
busybox sysctl -w kernel.random.read_wakeup_threshold=128

# Breaking the lease
# Prime Directive
echo "15" > /proc/sys/fs/lease-break-time

# Make perms all loosey-goosey
[ -d /sys/devices/system/cpu/cpufreq/ondemand ]


# Expand kernel perms
[ -e /dev/cpuctl/apps/cpu.notify_on_migrate ] && chown system.system /dev/cpuctl/apps/cpu.notify_on_migrate && chmod 0666 /dev/cpuctl/apps/cpu.notify_on_migrate

exit 0
